version: "2.2"

# these services are not intended to be launched,
# use sevices deriving that configuration placed in docker-compose.yml instead
services:
  redis:
    environment:
      IMPORT_DIR: /import
    image: redisgraph_test
    build: ./redis
    container_name: testredisgraph
    environment:
      REDIS_AUTH_USER: admin
      REDIS_AUTH_PASS: adminpasswd
    ports:
      - "6379:6379"
    volumes:
      - ./results/redis:/results
      - ./redis/setup:/setup
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  neo4j:
    image: neo4j_test
    build: ./neo4j
    container_name: testneo4j
    command: neo4j
    environment:
      NEO4J_AUTH_USER: neo4j
      NEO4J_AUTH_PASSWD: benchpasswd
      NEO4J_AUTH: neo4j/benchpasswd
      # IMPORT_DIR: /var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/setup:/setup
      - ./results/neo4j:/results

  neo4j-loader:
    image: neo4j_test
    build: ./neo4j
    container_name: testneo4j_launcher
    command: import
    environment:
      NEO4J_AUTH_USER: neo4j
      NEO4J_AUTH_PASSWD: benchpasswd
      NEO4J_AUTH: neo4j/benchpasswd
      IMPORT_DIR: /var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: "no"
    volumes:
     - ./neo4j/import:/var/lib/neo4j/import
     - ./neo4j/logs:/logs

  arangodb:
    image: arangodb_test
    build: ./arangodb
    container_name: testarangodb
    environment:
      ARANGO_ROOT_PASSWORD: benchpasswd
      IMPORT_DIR: /import
    ports:
      - "8529:8529"
    volumes:
      - ./results/arangodb:/results
      - ./arangodb/import/rel_ref_types.tsv:/cfg/rel_ref_types.tsv
      - ./arangodb/setup:/setup
