version: "2.2"

services:
# EUROVOC
  redis-eurovoc:
    extends:
      file: common.yml
      service: redis
    environment:
      RESULTS_DIR: /results/eurovoc
    volumes:
      - ./redis/queries_eurovoc:/queries
      - ./redis/import/eurovoc:/import
      - redis_data_eurovoc:/data

  neo4j-eurovoc:
    extends:
      file: common.yml
      service: neo4j
    environment:
      RESULTS_DIR: /results/eurovoc
    volumes:
     - ./neo4j/queries_eurovoc:/queries
     # - ./neo4j/import/eurovoc:/var/lib/neo4j/import
     - neo4j_data_eurovoc:/data

  neo4j-loader-eurovoc:
    extends:
      file: common.yml
      service: neo4j-loader
    volumes:
     - ./neo4j/import/eurovoc:/var/lib/neo4j/import
     - neo4j_data_eurovoc:/data


# PLWN
  redis-plwn:
    extends:
      file: common.yml
      service: redis
    environment:
      RESULTS_DIR: /results/plwn
    volumes:
      - ./redis/queries_plwn:/queries
      - ./redis/import/plwn:/import
      - redis_data_plwn:/data

  neo4j-plwn:
    extends:
      file: common.yml
      service: neo4j
    environment:
      RESULTS_DIR: /results/plwn
    volumes:
     - ./neo4j/queries_plwn:/queries
     # - ./neo4j/import/plwn:/var/lib/neo4j/import
     - neo4j_data_plwn:/data

  neo4j-loader-plwn:
    extends:
      file: common.yml
      service: neo4j-loader
    volumes:
     - ./neo4j/import/plwn:/var/lib/neo4j/import
     - neo4j_data_plwn:/data


volumes:
  redis_data_eurovoc:
  redis_data_plwn:
  neo4j_data_eurovoc:
  neo4j_data_plwn:
